// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package css

import "strconv"

const _TokenType_name = "IdentifierNumberStringSymbol"

var _TokenType_index = [...]uint8{0, 10, 16, 22, 28}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
